### PR TITLE
Add add/removeEventListener overloads from HTMLElement

### LINKED ISSUE #79: electron.d.ts error using TS2.6.0-rc in strict mode
```
node_modules/electron/electron.d.ts(5390,13): error TS2430: Interface 'WebviewTag' incorrectly extends interface 'HTMLElement'.
  Types of property 'addEventListener' are incompatible.
      Type '{ (event: "load-commit", listener: (event: LoadCommitEvent) => void, useCapture?: boolean | undef...' is not assignable to type '{ <K extends "error" | "waiting" | "progress" | "ended" | "change" | "input" | "select" | "abort"...'.
        Types of parameters 'listener' and 'listener' are incompatible.
          Type 'EventListenerOrEventListenerObject' is not assignable to type '(event: LoadCommitEvent) => void'.
            Type 'EventListenerObject' is not assignable to type '(event: LoadCommitEvent) => void'.
              Type 'EventListenerObject' provides no match for the signature '(event: LoadCommitEvent): void'.
```

I think it is due to this new strict change:
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#strict-function-types

### PR DESCRIPTION
**Pull request by sandersn**
WebviewTag adds electron-specific overloads to addEventListener and removeEventListener when it extends HTMLElement. However, it does not include the original overloads from HTMLElement, and Typescript does not include them when WebviewTag extends HTMLElement. This change adds those previously-missed overloads to WebviewTag. It is necessary to allow users of electron.d.ts to compile with Typescript 2.6 --strict.

Fixes #79

### CODE REVIEW

**Comment by danielweck** [comment]
Excellent, thank you!
This "bug" currently prevents from using TypeScript 2.6+ `strictFunctionTypes` in Electron projects.
(unless the line `interface WebviewTag extends HTMLElement` in `node_modules/electron/electron.d.ts` is patched with `@ts-ignore TS2430 (Interface 'WebviewTag' incorrectly extends interface 'HTMLElement')` ... which is of course not a viable option)
